import React from 'react';
import Link from 'next/link';

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white p-8 md:p-12 rounded-2xl shadow-sm border border-slate-200">
        <div className="mb-8 border-b border-slate-100 pb-6 flex justify-between items-end">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
            <p className="text-slate-500">Last updated: {new Date().toLocaleDateString()}</p>
          </div>
          <Link href="/" className="text-emerald-600 hover:text-emerald-700 font-medium text-sm">
            &larr; Back to Home
          </Link>
        </div>

        <div className="prose prose-slate max-w-none">
          <p>
            CreatorsXchange ("we", "us", or "our") respects your privacy and is committed to protecting the personal and store information you share with us. This Privacy Policy describes how personal information is collected, used, and shared when you install or use the CreatorsXchange App (the "App") in connection with your Shopify-supported store.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">1. Information the App Collects</h2>
          <p>When you install the App, we are automatically able to access certain types of information from your Shopify account:</p>
          <ul className="list-disc pl-6 space-y-2 mb-6">
            <li><strong>Store Information:</strong> We collect your shop domain, email address, and store settings to authenticate your account and provide you with our services.</li>
            <li><strong>Product Information:</strong> We sync product details (titles, images, inventory, pricing) to allow you to generate affiliate links and discount codes for your creators.</li>
            <li><strong>Order Information:</strong> We access order data (via webhooks) when an order is placed using a discount code or tracking link generated by our App. We only process order data necessary to calculate commissions and attribute sales to the correct creator.</li>
          </ul>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">2. How Do We Use Your Information?</h2>
          <p>We use the collected information in order to provide the Service and to operate the App. Additionally, we use this information to:</p>
          <ul className="list-disc pl-6 space-y-2 mb-6">
            <li>Communicate with you regarding updates, support, or billing.</li>
            <li>Generate tracking links and discount codes on your Shopify store.</li>
            <li>Track real-time affiliate sales and calculate commissions for your creators.</li>
            <li>Provide analytics and insights within your CreatorsXchange dashboard.</li>
          </ul>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">3. Sharing Your Personal Information</h2>
          <p>
            We do not sell your personal or store information to third parties. We may share your Personal Information to comply with applicable laws and regulations, to respond to a subpoena, search warrant, or other lawful request for information we receive, or to otherwise protect our rights.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">4. Data Retention</h2>
          <p>
            When you install the App and connect your store, we will maintain your Order Information and Product Information for our records unless and until you ask us to delete this information. If you uninstall the app or disconnect your store, tracking and synchronization will stop immediately.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">5. Changes</h2>
          <p>
            We may update this privacy policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal, or regulatory reasons.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">6. Contact Us</h2>
          <p>
            For more information about our privacy practices, if you have questions, or if you would like to make a complaint, please contact us by email at <strong>partner@creatorsxchange.com</strong>.
          </p>
        </div>
      </div>
    </div>
  );
}
